// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajgwemhakkaheaokglbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZ3dlbWhha2thaGVhb2tnbGJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDk4MjksImV4cCI6MjA1NzE4NTgyOX0.c61rFHVOidus8ebvefYCgGT03Gc7o4YZc8RXzBIgCxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);